WildCodeSchool/orleans-php-2003-project-coachpeter

.gitignore, assets/scss/_vars.scss, assets/scss/app.scss, package.json, src/Controller/HomeController.php, templates/base.html.twig, templates/home/home.html.twig, yarn.lock
firsts SCSS variables and creation of the first / road
=> initialisation repo

assets/scss/_actuality.scss, assets/scss/app.scss, src/Controller/HomeController.php, src/Entity/Actuality.php, src/Repository/ActualityRepository.php, templates/home/_actuality.html.twig, templates/home/home.html.twig
Ajout de la partie vue Actualité pour la home, 
Ajout de l'entité Actualité 
Modification de la methode index dans le homeController
Ajout du fichier CSS lié
=> S01 us35 actuality

templates/admin_actuality/_delete_form.html.twig, templates/admin_actuality/index.html.twig
fonctionalité delete + modif vue pour homogénéité
=> S03us57 delete actu

assets/scss/_activity.scss, src/Controller/HomeController.php, templates/home/_activity.html.twig
alignement des boutons de contact et limit de 3 activités à l'affichage de la home
=> Fix home activites

src/Controller/TransformationController.php, src/Form/TransformationType.php, templates/_admin_navbar.html.twig, templates/admin_transformation/_delete_form.html.twig, templates/admin_transformation/_form.html.twig, templates/admin_transformation/edit.html.twig, templates/admin_transformation/index.html.twig, templates/admin_transformation/new.html.twig, templates/admin_transformation/show.html.twig
Mise en place CRUD admin Transformation - Page consultation ok - intégration du DELETE dès la page d'accueil - harmonisation avec autres vues Admin
=> S03_US22 Mise en place admin Transformation et mise en page index

config/packages/security.yaml, src/Controller/SecurityController.php, src/DataFixtures/UserFixtures.php, src/Entity/User.php, src/Repository/UserRepository.php, src/Security/LoginFormAuthenticator.php, templates/_navbar.html.twig, templates/security/login.html.twig
page log créer et ajout des liens vers la navbar
=> S03us37 log

assets/scss/_activity.scss, src/DataFixtures/ActivityFixtures.php, templates/_admin_navbar.html.twig, templates/home/_activity.html.twig
Correction affichage activité, ajout du "alt", affichage picto et ajout lien navbar admin pour retourner sur le site côté visiteur.
=> Correction Home responsive activité

src/Controller/TransformationController.php, src/Entity/Transformation.php, src/Form/TransformationType.php, templates/admin_transformation/edit.html.twig
update & delete transformation ok
=> S04_US22_Transforfation update & delete ok

src/Controller/RegistrationController.php, src/Controller/SecurityController.php, src/DataFixtures/UserFixtures.php, src/Entity/User.php, src/Form/RegistrationFormType.php, templates/_navbar.html.twig, templates/registration/register.html.twig, templates/security/login.html.twig
Intégration de l'ajout d'un nouvel user, ajout de l'information sur la navbar avec possibilité de deconnexion
=> SP05US71 Registration

assets/scss/navbar.scss, templates/_admin_navbar.html.twig
Pour avoir un visuel un peu plus clean
=> Fix navbar admin

src/Controller/AdminUserController.php, templates/admin_theme/_delete_form.html.twig, templates/user/_delete_form.html.twig, templates/user/index.html.twig
Possibilité de supprimer un client par l'admin
=> S05us14 supp client

templates/_admin_navbar.html.twig
possibilité de se deconnecter depuis la navbar
=> fix_admin_navbar

src/Controller/UserProfilController.php, templates/_navbar.html.twig, templates/member/profil.html.twig
accès à une page mon profil pour voir les infos
=> S05us77 membre profil

templates/admin_program/_form.html.twig, templates/admin_program/edit.html.twig, templates/admin_program/new.html.twig
=> S05 us82 add program

templates/admin_user/index.html.twig
L'inclusion du formulaire avait sauté suite à la refactorisation du dossier
=> reintroduction du formulaire de suppression client

config/packages/vich_uploader.yaml, src/Controller/AdminRessourceController.php, src/Entity/ProgramStep.php, src/Entity/Ressource.php, src/Form/RessourceType.php, src/Repository/RessourceRepository.php, templates/admin_ressource/_delete_form.html.twig, templates/admin_ressource/_form.html.twig, templates/admin_ressource/edit.html.twig, templates/admin_ressource/index.html.twig, templates/admin_ressource/new.html.twig, templates/admin_ressource/show.html.twig, templates/home/_about_me.html.twig
Ajout table Ressource :
- lien Theme ok
- liens programStep ok
- upload fonctionnel
=> S06 us76 ressources index

src/Controller/AdminProgramStepController.php, src/Form/ProgramStepType.php, templates/admin_activity/_form.html.twig, templates/admin_program/index.html.twig, templates/admin_program_step/_form.html.twig, templates/admin_program_step/new.html.twig, templates/home/_about_me.html.twig
deAdmin Program_index => Ajout Etape => page ProgramStep_new avec transmission id_Program ok
=> S06 us16 esthetisme add program step

src/Controller/AdminActivityController.php, templates/admin_activity/index.html.twig
Dans l'index admin des activité, la catégorie ne s'affichait plus. c'est corrigé
=> Fix affichage des category dans admin activite index

src/Entity/ProgramStep.php, templates/member/index.html.twig
Affichage programme en fonction des dates + assert
=> Fix membres

src/Form/ActualityType.php, src/Form/AttendedEditType.php, src/Form/AttendedType.php, templates/base.html.twig
pour avoir un champ au lieu de 3 selecteurs et pouvoir préciser par defaut la date du jour
=> Champ date

src/Controller/AdminActualityController.php, src/Form/ActualityEditType.php
pour éviter la reprise de la date du jour dans l'édition
=> modif formulaire actualité

config/packages/doctrine_migrations.yml, src/Entity/User.php
ajout des espaces manquants pour les asserts
=> FIX - Admin User Edit - Message d'erreur #257 

src/Controller/AdminUserController.php, src/Form/AdminUserType.php, templates/admin_user/_form.html.twig
ajout deuxième form pour que Peter ne puisse pas modifier les infos clients
=> #300 fix admin gestion client

config/packages/security.yaml
Route page profil restreinte à partir du role USER
=> Fix profil#285

src/Entity/Degree.php
ajout du ? dans setter organisme
=> fix_admin_certif#292

src/Controller/AdminDegreeController.php, src/Controller/HomeController.php
affichage par ordre chrono du plus récent au plus ancien
=> Fix_admin_certif_affichage#289

src/Entity/User.php
pour avoir le message d'erreur quand les champs sont vide plutôt qu'une erreur 500
=> Fix_modif_profil#276

templates/WhoIAm/index.html.twig
=> Fix 277 routes images

src/Entity/Activity.php, src/Entity/Actuality.php, src/Entity/InfoCoach.php, src/Entity/Program.php, src/Entity/ProgramStep.php, src/Entity/Ressource.php, src/Entity/Theme.php, src/Entity/Transformation.php
ajout des espaces pour les asserts
contient le fix issue #261
=> Fix_Assert

assets/scss/member.scss, templates/member/index.html.twig
=> FIX_ESPACE MEMBRE #304

src/Entity/Activity.php, src/Entity/Program.php
=> Fix 260 program duration

templates/admin_user/index.html.twig, templates/member/profil.html.twig
pour gérer l'affichage dans mail trop long #301
rectifié aussi côté visiteur
=> Fix_client_admin_mail#301

src/Entity/Degree.php
Ajout assert #291 . Ne pas pouvoir mettre une année de fin antérieure au début
=> Fix_certif#291

src/Controller/AdminProgramController.php, templates/admin_program/index.html.twig
=> Fix 297 program ordre etapes

assets/scss/app.scss, templates/WhoIAm/index.html.twig, templates/transformations/index.html.twig
=> Fix_h1_style

templates/security/login.html.twig
#286 
pour que la création de compte soit plus lisible
=> creer un compte bouton

src/Entity/Ressource.php, templates/member/index.html.twig
Ordre ASC des étapes côté membre + responsive Phone-Tablet-Desktop
=> Fix affichage etapes

assets/scss/transformations.scss, templates/transformations/index.html.twig
rajout de contraintes de tailles maxis et object-fit
=> fix_transformations

src/Entity/User.php
suppression role admin dans la constante #299 
il n'y a plus de choix "administrateur"
=> Fix_admin_gestion_client

templates/admin_activity/index.html.twig
rajout de text-break pour préservation d'affichage
=> fix_activite_Admin

templates/_navbar.html.twig
=> Fix_Connexion

src/Controller/ContactController.php, src/Form/ContactType.php, templates/contact/contact.html.twig
Adding helpers for contact form
=> FIX_contact_form_helpers

templates/home/_activity.html.twig
=> fix affichage description activités

templates/coaching/index.html.twig, templates/team/index.html.twig
conditions twig pour toujours afficher un picto et update chemin asset build
=> fix affichage pictogrammes

assets/scss/app.scss, templates/WhoIAm/index.html.twig, templates/actuality/index.html.twig, templates/coaching/index.html.twig, templates/home/_activity.html.twig, templates/home/_before_after.html.twig, templates/team/index.html.twig
h1-h2 uniformisation titre + responsivve
=> Fix_h1-h2 responsive

templates/home/_about_me.html.twig, templates/home/_activity.html.twig
demande du client, ne garder qu'un seul bouton sur les 3 d'origine
=> Fix_bouton me contacter home

templates/home/_activity.html.twig
=> bouton  me contacter

src/Controller/AdminActualityController.php
=> fix_admin_index

templates/home/_headband.html.twig
demande de Peter de modifier le text:
➡️Est il possible de modifier les noms sous le logo de la page d’accueil :
Coach spécialisé en sport - nutrition - santé à orléans
Par
Sport - santé - nutrition
=> Fix_text_headband

templates/WhoIAm/index.html.twig
demande de Peter:
Dans « QUI SUIS-JE »
➡️Est-il possible de remplacer « mes certifications » par « mes diplômes »
=> modif certification en diplôme

src/Form/ActivityType.php
=> Correction picto

templates/WhoIAm/index.html.twig
intégration du text donné par Peter
=> Qui-suis-je contenu

src/Controller/TeamTrainingController.php, templates/home/_activity.html.twig
demande de Peter
➡️J’aimerai qu’il soit possible de cliquer sur l’une des 3 photos ou texte présenté qui dirige vers la page concernée.
=> ajout lien vers page categorie
